3dmark/ul3dmark.py
blender_render/blender.py
blenderbenchmark/blender.py
cinebench_2024/cinebench.py
cinebench_2024/cinebench_utils.py
gravitymark/gravitymark.py
gravitymark/gravitymark_utils.py
superposition/superposition.py

- Added `unit` properties to each report.json missing one.
- Updated the test names to be more display friendly

Update non-game benchmark report jsons

---

blender_render/blender.py
blenderbenchmark/blender.py
superposition/superposition.py

Some of the tests have API choices!

Add API to test name for reports

---

7z/sevenzip.py
7z/sevenzip_utils.py
CHANGELOG.md

- Lock to specific version and download from the network drive.
- Iterate 3 times per invocation.

Update 7zip harness

---

F1_23/f1_23.py
harness_utils/misc.py

artifact manager implementation for f1 23, cleaned up functions that were no longer necessary and added regex search function to find latest result file

F1 23 Artifact Manager Implementation

---

total_war_warhammer_iii/twwh3.py

results screenshot and saving of config file at the end of the run

Artifact Manager Implementation for Total War Warhammer 3

---

grid_legends/grid_legends.py

Artifact  manager implementation for grid legends test. Moved some variables relating to configs out of a function so they can be reused by the artifact manager later in the code

Grid Legends Artifact Manager Implementation

---

the_last_of_us_part_i/the_last_of_us_part_i.py

Added screenshots of display settings and graphics settings, working, ready for showtime

Tlou add screenshots

---

F1_24/f1_24.py

change timeout for slow launcher f1_24

---

returnal/returnal.py

fix function keras

---

CHANGELOG.md
handbrake/handbrake.py
handbrake/handbrake_utils.py

Harness update for handbrake to version 1.9.1

Handbrake Harness update

---

CHANGELOG.md
aots-e/aotse.py
aots-e/aotse_utils.py
aots-e/manifest.yaml

Update to the Ashes of the Singularity: Escalation harness to include PresentMon logging.

Ashes of the Singularity Update

---

assassins_creed_shadows/acshadows.py
assassins_creed_shadows/manifest.yaml

AC shadows harness all working awaiting variance trials

Ac shadows harness

---

pugetbench/manifest.yaml
pugetbench/pugetbench.py

jons requested feature for pugetbench, he wants to choose which version he can use if he so desires

puget_bench benchmark ver

---

assassins_creed_shadows/acshadows.py

changed my botched f strings  and added a longer timeout

Ac shadows fixes

---

dota2/dota2.py

added scaling multiple so click lands on all resolutions
and some linting

added scaling multiple so click lands on all resolutions

---

assassins_creed_shadows/acshadows.py

some systems need spacebar to be pressed on unkown hardware or driver

Ac hardware skip

---

assassins_creed_shadows/acshadows.py

Ac hardware

---

harness_utils/output.py

- change the any typing to dict

this was on a to-do stickynote

---

stellaris/stellaris.py

Added a few lines for patch notes handling if it does pop up

Close patch notes

---

7z/sevenzip_utils.py
blender_render/blender_utils.py
cyberpunk2077/cyberpunk_utils.py
dota2/dota2_utils.py
godot_compile/godot_compile_utils.py
handbrake/handbrake_utils.py
stellaris/stellaris_utils.py
the_last_of_us_part_ii/tlou2.py
xz/xz_utils.py

changed the L drive mappings to match the newest windows procedure

L drive mapping
